### ISSUE TITLE
Produce an SPH recording loop

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto#293]
We need to generate an SPH looping recording from Sibernetic to use in the WormSim.

Strategy:
- Identify the first timestep T0
- Identify the last timestep T1>T0 
    - so that position of cuticle and muscles at T0 is the same as the position of cuticle and muscles at T1 (minus the offset of how much the worm has moved)

Dump to a file for the given segment (T0->T1) of simulation containing (each item below is a file)
- [x] particle positions for cuticle
- [x] particle positions muscle cells
- [x] membranes information (triangulation) for cuticle 
- [ ] membranes information (triangulation) for muscles (NEW)
- [x] activation signals for each muscle cells (NEW)

**Comment by gidili** [comment]
Hey @skhayrulin any progress with this?

**Comment by skhayrulin** [comment]
Hi Giovanni!

Yes I've got a news, I think I finished with C++ code and I recorded
trajectory of movement, but there was no updates from me because It's
holidays in Russia:) it'll finish 12 November.

Sorry for delay
All best in new year:),
Sergey

2015-01-04 19:00 GMT+06:00 Giovanni Idili <notifications@github.com>:

> Hey @skhayrulin <https://github.com/skhayrulin> any progress with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openworm/org.geppetto/issues/293#issuecomment-68632052>
> .
>



-- 
Best regards,
 Khayrulin Sergey

**Comment by gidili** [comment]
This is done! Currently under review by @gitmado.

Thanks @skhayrulin :)
