### ISSUE TITLE
Design Export feature for a ModelInterpreter

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#313]
##### CORE

 - [x] We need to extend IModelInterpreter to add an interface for exporting the model (writeModel)

##### FRONTEND

 - [x] We need to extend GeppettoInbound and Outbound messages to deal with the new request from the client and the new response from the server
 - [x] We need to extend the ServletController with the new method

##### SIMULATION

 - [x] We need to add logic to the SimulationService to go and ask  the appropriate ModelInterpreter that needs to be used to get the model tree
 - [x] Define how the server gives back the model to the client, is it binary? Is it text? Is it packaged? Is it compressed?

- [x] Define interface
- [ ] Create sequence diagram for the interactions

#### Client side

- [x] Expand the API of Aspect
- [x] Implement the API for writeModel, what happens when the command is issued? It returns automatically and then when the response from the server is available the download starts automatically?

##### MODEL.NEUROML

 - [x] An implementation for the writeModel method needs to be added
 - [x] A "not available" response for the server needs to be defined in case there's a problem with the operation, in that case the client will inform the user

##### OTHER

 - [x] Add "not available" response to other existing Modellnterpreters in their implementation

#### Pending questions

- [x] How does the client know which formats are supported by a given model interpreter? The server needs to send a map to the client on startup specifying what are the available options and the client in turns will save this and use this information when creating for instance the context menus in the widgets

**Comment by pgleeson** [comment]
@adrianq @tarelli, I realise that this mainly requires development on the Geppetto side, but it would be good still to have a corresponding issue open in the OSB repo with a user level description for how they will be able to access this functionality with existing/future NeuroML widgets or through the main OSB interface.

**Comment by adrianq** [comment]
@pgleeson I think this issue I created in our OSB repo https://github.com/OpenSourceBrain/redmine/issues/142 should cover this. Basically I think we should have a very detailed and interactive tutorial and, eventually, we can create a video from it and show it in the OSB documentation. A good start could be creating a sort of script in a google docs so we can decide what and how to explain things to the users. Geppetto already has a tutorial so this can give us some ideas about a nice way to do it.

**Comment by pgleeson** [comment]
I didn't really mean this in the sense of instructions for how there user should use it, more a set of use case descriptions for what's planned, so that it can help/ensure compatibility with the Geppetto implementation, e.g.

- User gets list of export options in [main Control panel](https://github.com/OpenSourceBrain/redmine/issues/146)...
- User can export individual model elements (e.g. channel) to certain formats (e.g. Neuron mod file) in corresponding summary widget
- When a LEMS simulation is loaded a "full" simulation is downloadable, e.g. Neuron with main Python script.

Questions....

- Is the decision made that a certain component is exportable to format X made before the widget is loaded?
- A user gets a zipped/tarred? download..?
- User can view exported files online before downloading..?
