### ISSUE TITLE
Connectivity widget improvements

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#323]
- [x] Improve readability of node names
- [x] Improve styling of drop down
- [x] Add documentation for how to use the widget
- [x] Document the code, see http://127.0.0.1:8080/org.geppetto.frontend/jsdocs/Connectivity.html
- [x] Add ability to link properties of the connectivity widget (colour, edges, etc.) to domain specific (or any other kind) information

**Comment by borismarin** [comment]
The "original" connectivity widget prototype also had "force layout" and "hive plot" modes, besides the connectivity matrix. @slarson has recently asked me about hive plots, any news on that front @adrianq @tarelli?

**Comment by borismarin** [comment]
I also had chord plots; another thing TBD is using the connectivity data to calculate network metrics (opening up a whole new world - the "data analysis perspective" in geppetto); in my prototype, I could directly use networkx over the structs, as I had a Python / is hybrid. Not quite sure if we want to stick to pure js forever (even though [some of networkx has even been ported to js](http://felix-kling.de/JSNetworkX/) , so that would be also an opportunity to discuss geppetto bindings to other envs.
