### ISSUE TITLE
Decide on use of "Systems Biology Open Simulation Platform"

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#330]
Might need to change "Systems Biology Open Simulation Platform" - Sys Biol is a field with a well defined idea what it does, namely subcellular signalling pathways, genetic regulation networks... and SBML/CellML are their chosen formats... Using this term for Geppetto will confuse/annoy people in that field...

Is Geppetto even biology specific..?

**Comment by tarelli** [comment]
@pgleeson The requirements of Geppetto came from OpenWorm initially and the idea of simulating the whole organism, hence where systems biology was coming from, I know though what you are saying and I see your point. Computational biology is what the website says and it's broader and less controversial than systems biology I think; anyway that tagline in the git repo was there since a long time and I just removed the "Systems biology" bit leaving for now "Open Simulation Platform" which is more generic.

**Comment by pgleeson** [comment]
Ok, sounds good.
