### ISSUE TITLE
Prototype multiple aspects integration

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#361]
High level design is [here](https://github.com/openworm/org.geppetto/issues/307).

**Comment by dkruchinin** [comment]
The prototype is ready. It's still very fragile, so don't expect much from it. Basically it just demonstrates that way several aspects can communicate. A receiving aspect doesn't really map the variables it receives onto something else, it just prints them to the log file for now.

To get the sources, check out the branch "channels" from org.geppetto.core, org.geppetto.simulation and org.geppetto.simulator.jlems. The first one contains basic channels and ports primitives, org.geppetto.simulation contains the code responsible for sending and receiving variables and org.geppetto.simulator.jlems has a knowledge of how to find requested variable in the LEMS based simulation (note that each simulator will have to implement its own way of finding requested variables in the simulation results).

Since the code responsible for simulation is refactoring, as well as the way a simulation is configured, I didn't add a way to configure channels and variables mappings besides the java API. SimulationService.start() method contains a chunk of code responsible for creation and configuration of channels and variables I used for testing. I used HH together with SPH "single muscle cell" making the former send some variables to the latter.

The simulation files I used can be downloaded from here: https://www.dropbox.com/s/yk5j78oyowweghu/sim.tar.gz?dl=0 (Note: after downloading open GEPPETTO.xml and change mdelURL paths to point to a correct directory)

**Comment by tarelli** [comment]
@dkruchinin thanks Dan, I skimmed through the code, it's looking good! How about you walk us through it at the Geppetto meeting next Tuesday? I think we'll have to treat integration capabilities as a Feature that can be implemented or not by a given simulator, there is a [refactoring](https://github.com/openworm/org.geppetto/issues/360) ongoing for that so this will be another candidate for it once @jrmartin is done, the idea is to keep ISimulator as simple as possible.

**Comment by dkruchinin** [comment]
@tarelli > How about you walk us through it at the Geppetto meeting next Tuesday?

Sure.
