### ISSUE TITLE
Implement show units for watched variables

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#395]
- [x] Units need to be extracted from LEMS
- [x] Units need to be shown in the plot widget
- [x] Units need to be shown in the tree visualizer widget
- [x] Units need to be shown in the variable widget

**Comment by adrianq** [comment]
A bit of code that can be useful to solve this issue:
https://github.com/NeuroML/org.neuroml.export/blob/16284a22f817ce13ad4f58a5bc68add5e63fd687/src/test/java/org/neuroml/export/utils/UtilsTest.java#L130

**Comment by adrianq** [comment]
Done!
@tarelli Look at this: https://github.com/openworm/org.geppetto.simulation/blob/datamanager/src/main/java/org/geppetto/simulation/RuntimeExperiment.java#L131 

I am not populating the simulation tree with the list of watched variables when status is queued. If status is queued is because we are going to run the simulation and we will be calling the populateSimulationTree in the ExperimentRunManager. Is this correct? Shall we consider any other status?
