### ISSUE TITLE
More info on experiments with errors

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#445]
What can be done to see logs/more info for experiments that show up as errored?

![selection_731](https://cloud.githubusercontent.com/assets/1556687/9994731/9699bd36-6076-11e5-8cb0-3c72bb0ebd63.jpg)

**Comment by tarelli** [comment]
Currently only on the server logs (/serviceability/logs/) but it could definitely improve!

**Comment by pgleeson** [comment]
In this specific case it may have been due to nothing watched/recorded. Maybe catch this scenario and warn that there's no point in running a simulation in that case...

Is there an example script containing console commands for watching/recording variables, then replotting them once the simulation comes back? Have seen @adrianq cutting pasting commands to get geppetto to save/plot variables in "fresh" neuroml project/experiments.

**Comment by adrianq** [comment]
@pgleeson If you are not watching/recording anything, this shouldn't be problem. The conversion from NeuroML to Neuron done by the export library should work, right? And Neuron shouldn't have a problem about this either. The only one thing is that afterwards you can't plot or analyse any result as anything but the time step will be recorded in the server.

Regarding the magic scripts you saw me copy&pasting :) , here you can find some examples and a brief explanation about them:

//TO run
- Project.persist(); (this is the same as clicking on the star button, you should be logged in in order to do this in OSB)
- MediumNet.baskets_12_0.electrical.getSimulationTree() (In this case, I am extracting all the variables that can be wathced in a cell (baskets_12_0) in a network(MediumNet). You may want to get all the variables from a network but don't ask too much content to Geppetto until we have the type/instance refactor done it can't be too much information for the browser to deal with.)
- MediumNet.baskets_12_0.electrical.SimulationTree.bask[0].v.setWatched(true) (Variable you would like to watch. After SimulationTree it follows the same path format than in NeuroML)
- Change Manually length and timestep for instance to 0.3 and 0.00001
- Press run button

//TO reproduce
- MediumNet.baskets_12_0.electrical.getSimulationTree();
- G.addWidget(0).plotData(MediumNet.baskets_12_0.electrical.SimulationTree.bask[0].v);
- G.addWidget(5).setVariable(MediumNet.baskets_12_0.electrical.SimulationTree.bask[0].v);
- Project.getActiveExperiment().play({step:1}); (this will stream the results step by step)
- Project.getActiveExperiment().play({playAll:true}); (this will stream all at once. Again if there are too many steps it can make your browser crash)

Any doubt, tomorrow I will be on the desktop just behind you :)
