### ISSUE TITLE
Cells without morphology being displayed multiple times

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#461]
See http://www.opensourcebrain.org/projects/izhikevichmodel?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FIzhikevichModel%2Fmaster%2FNeuroML2%2FFiveCells.net.nml

https://github.com/OpenSourceBrain/IzhikevichModel/blob/master/NeuroML2/FiveCells.net.nml.

Note these are Izhikevich cells, and like the I&F cells in the c302 model, have no explicit morphology (and so are represented by spheres of arbitrary size). Nevertheless, they should be just represented by 5 spheres in Geppetto. 

This feature (broken?) would help identify which are the correct cells: https://github.com/openworm/org.geppetto/issues/397

**Comment by pgleeson** [comment]
This may be related to the above, again "ghost" cells. Seems like there are 2 instances of the cells, one selectable & the other mirrors at 2x the spatial dimensions:

http://opensourcebrain.org/projects/weileretal08-laminarcortex?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FWeilerEtAl08-LaminarCortex%252Fmaster%252FNeuroML2%252FCortexDemo.net.nml#

![selection_780](https://cloud.githubusercontent.com/assets/1556687/10511330/5e5f3866-7330-11e5-8e95-9564ff214aa3.jpg)

**Comment by tarelli** [comment]
Yup looks like the same problem, will investigate!

**Comment by pgleeson** [comment]
@tarelli @adrianq Any update on the status of this issue post refactor?

**Comment by adrianq** [comment]
@pgleeson Looking good now! ![screenshot from 2016-01-27 11 42 18](https://cloud.githubusercontent.com/assets/6850223/12612684/823c73e4-c4ec-11e5-9063-972d689def43.png) 

I am still checking the second one as I am getting an exception in the infowriter of the export library...

**Comment by adrianq** [comment]
The other model is working properly as well:
![screenshot from 2016-01-27 12 12 14](https://cloud.githubusercontent.com/assets/6850223/12613123/761a448a-c4ef-11e5-9aba-e31d197cab04.png)

The problem in the export lib is because when creating the summary (info writer) we are calling a [method to convert a standalone component into a lems component](https://github.com/NeuroML/org.neuroml.export/blob/master/src/main/java/org/neuroml/export/info/InfoTreeCreator.java#L194). This method is not going to work with components like [this one](https://github.com/OpenSourceBrain/WeilerEtAl08-LaminarCortex/blob/master/NeuroML2/CortexDemo.net.nml#L6) as it requires another component, i.e. it has a component reference (AMPAR in this case). When resolving the lems document it fails as it can't found the component with id=AMPAR.

Closing this issue anyway as this error is about the export library...
