### ISSUE TITLE
Ensure correct location of connection lines on pre/post segment for 3D cells

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#463]
Many of the networks in NML2 have connections of the form:

```
<connection id="137" preCellId=... postCellId=... preSegmentId="1" preFractionAlong="0.1" postSegmentId="6" postFractionAlong="0.2"/>
```

i.e. the connection starts at point 0.1 along segment 1 on pre cell & connects to 0.2 on seg 6 on post cell.

This is not reflected in the displayed connections: all are from point 0 on segment 0... e.g. [ACNet2](http://opensourcebrain.org/projects/acnet2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FACnet2%2Fmaster%2FneuroConstruct%2FgeneratedNeuroML2%2FMediumNet.net.nml)

@tarelli didn't someone look into this in the past? Is there a partial implementation of this?

**Comment by pgleeson** [comment]
@tarelli did you manage to find the old code that tried to address this issue?

**Comment by tarelli** [comment]
@pgleeson there were some bits in the model to have the pointer to the segment but this will have to be properly looked at as the information was not used. Also a drawback of pointing to the exact part of the cell is that the geometries of all the cells would have to be split for this to happen which will have performance implications (atm we split them only to display visual groups and when replaying multicompartments but this addition would make them basically always split which would bring down the number of fps). Ad interim I have however implemented an improvement for connections whereby now the number of synapses is not entirely neglected and the more there are the thicker the connection line will be displayed, see screenshot. I've also fixed a number of pre-existing bugs whereby the lines were not always of the right colour and sometimes they were not matching the connections due to some caching.

<img width="1443" alt="screen shot 2016-01-29 at 10 49 32" src="https://cloud.githubusercontent.com/assets/81127/12673671/03c6ffb2-c676-11e5-9c75-e62bd4dea209.png">
