### ISSUE TITLE
Cannot load large 3D model

### ISSUE THREAD

**Issue by JustasB** [openworm/org.geppetto#469]
I have a model with about 6000 cells, 635 of the cells have complex morphology, and another ~5000 are simple 3-segment cell models. This is a "reduced" model, the full model has 635 complex cells and ~120,000 simple cells.

When I try loading the reduced model, Geppetto shows the spinner and then errors out with ~"cannot communicate with server. refresh page." error.

Any tips on how to load large models in Geppetto? Alternatively, if the model is hitting some limit, could that be shown as a message to the user?

This is the network file:
https://raw.githubusercontent.com/JustasB/Mig3DTest/master/NeuroML2/Networks/Bulb_635MC_5635GC.net.nml

And this is the Geppetto link:
http://opensourcebrain.org/projects/d-olfactory-bulb-network?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FJustasB%252FMig3DTest%252Fmaster%252FNeuroML2%252FNetworks%252FBulb_635MC_5635GC.net.nml

This may be related to: https://github.com/openworm/org.geppetto/issues/363

**Comment by tarelli** [comment]
@JustasB the next release of geppetto will be much better at handling big models. Said so describing large scale models with a specification of each cell and each connection where every instance definition is duplicated individually represented is doomed to break for any standard and any tool, including geppetto. There are different groups tackling these problems and this is for instance where conversations about "rules" and algorithmic descriptions of the model and the connections come into play. 

In addition to the above I see that in the model you have there is a population for each cell and one projection for each connection as if all the cells were all of a different class. This is a pattern I have seen in different script generated NML models and although I know it is easy to create with a script such a model it is then very impractical to handle it in an efficient way. It is likely that the difference between the majority of those cells is probably some parameter which should not be translated in redefining the whole cell (i.e. creating a new ComponentType) altogether otherwise we are dealing with an already hard problem in a too naive way. 

How many different cell types (with the same morphology and dynamics) are in the model leaving aside those that differ for only having different parameters? Ideally there should be only one population per class in which only the parameters that are different are then explicitly represented. Such mechanisms will now be supported in Geppetto to push as much as possible the size of models that can be handled but they will also have to be supported by NeuroML to begin with and I don't know if that's possible at the moment (cc @pgleeson).
If Geppetto will receive thousands of different component types it can only deal with them separately which of course won't take advantage of instance/class concepts and will be doomed to work only up to a "small" size.

**Comment by JustasB** [comment]
I agree, having a class and then varying the instances by a param would be way more efficient. So is the number of types that is the biggest factor for this model?

It would probably be easiest to convert the 120k+ granule cells into one Type and then have each cell as an instance. The GCs vary only a few parameters between cells.

The mitral cells, 635 of them, on the other hand, each have their own morphology trees. Only channel definitions are the same across the cells. I could do a Type inheritance thing where a base mitral cell defines all the channels, and then a sub type defines it's own morphology. Not sure how much that would help performance wise.

**Comment by tarelli** [comment]
Yes, in the new version of Geppetto types are getting created from the get go and instances only on demand, so to optimise a model we need to reuse types as much as possible. This obviously won't only help the tools coping with large models but also the maintainability of the model itself.
