### ISSUE TITLE
Cancer Immunology Systems Biology

### ISSUE THREAD

**Issue by jacobmcpherson** [openworm/org.geppetto#485]
So I'm brand new to this, and I can tell there is a ton of coders here, but I am a molecular cell biologist. I want you guys to make a dynamic 3D systems biology modeling simulator for the different immune cells and cancer cells, down to their molecular cross-talk conversations. Is this possible?

**Comment by tarelli** [comment]
@jacobmcpherson thanks for your interest in Geppetto! Everything is possible ;) Many of the big features that we developed so far, comparable to what you are describing, e.g. support for a new class of models/simulator, usually happens because of either volunteer effort by one or more contributors or because of some collaboration with a research lab which has resources (money and/or people) to invest in the task. If you fall in either of these categories I'd be happy to schedule a meeting!
