### ISSUE TITLE
Add a Python console to Geppetto

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#489]
A Python console would enable Geppetto to expose the [Python API] from the frontend. The Python console could be an alternative to the Javascript one. Some Python commands would be mapped to their JS counterpart, for say anything that has to interact with the UI.

**Comment by borismarin** [comment]
What's the status of client (browser!) side python interpreters? People
have been trying that for a while, from direct cpython-> js compilation
(via emscripten, see Brython), to nicer pypy/llvm/asmjs (see pypyjs)?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/openworm/org.geppetto/issues/489>

**Comment by petepy** [comment]
I like this idea! another option I like is a full bash shelI. if user's could launch their own workspace from the dashboard and have in browser IDE like features for custom projects, It would be awesome. Check out c9.io for an example. Obviously , code editing would not be the focus, but a useful feature.

**Comment by borismarin** [comment]
we will be discussing ide-like online editor functionality (via eclipse
orion / ace / codemirror) in the codegen hackaton.

**Comment by tarelli** [comment]
One option is to integrate Jupyter notebook in Geppetto, @borismarin  is starting to experiment with this

**Comment by borismarin** [comment]
see https://github.com/borismarin/org.geppetto.python/tree/frontend-experiments

**Comment by borismarin** [comment]
more generic: #442 (design python API)
