### ISSUE TITLE
OSB Explorer link fails to load a 120 cell network

### ISSUE THREAD

**Issue by JustasB** [openworm/org.geppetto#583]
When I run the following OSB Explorer URL to load a [120 cell NeuroML network](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NeuroML2/Networks/Bulb_30MC_90GC_OdorIn.net.nml) in Gepetto:

http://www.opensourcebrain.org/projects/miglioreetal14_olfactorybulb3d?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FMiglioreEtAl14_OlfactoryBulb3D%2Fmaster%2FNeuroML2%2FNetworks%2FBulb_30MC_90GC_OdorIn.net.nml

I see the spinner, with the loading message, and after 1-2 minutes, I see the following error:
![image](https://user-images.githubusercontent.com/10732358/35937822-9d68f6c2-0c04-11e8-9088-6ba74dbc8e45.png)

A smaller version of the same network with 15 cells, loads without errors:
http://www.opensourcebrain.org/projects/miglioreetal14_olfactorybulb3d?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FMiglioreEtAl14_OlfactoryBulb3D%2Fmaster%2FNeuroML2%2FNetworks%2FBulb_5MC_10GC.net.nml

![image](https://user-images.githubusercontent.com/10732358/35937964-06a02ca0-0c05-11e8-9def-fd171fee250a.png)

**Comment by mattearnshaw** [comment]
hi @JustasB 

thanks for the report – could you try the 120 cell model again? I've made some changes to help prevent chrome running out of tab memory and it loads OK for me now.

The model will be rendered as lines rather than 3D. In principle it can be changed using the `network_Migliore2014.setGeometryType('cylinders')` command, but this crashes the chrome tab again for me.

Firefox is a bit better behaved with these memory issues, so you might have better luck there.

**Comment by JustasB** [comment]
Thank you @mattearnshaw. I no longer get the error.
