### ISSUE TITLE
Move webapp outside of org.geppetto.frontend

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#602]

**Comment by rodriguez-facundo** [comment]
this has already been done:

- The content of webapp now lives in geppetto-client repo.
- The content of extensions/geppetto-default now lives in geppetto-application repo.

geppetto-client repo also exists as a npm package (@geppettoengine/geppetto-client), so instead of geppetto-client containing geppetto-application, we have geppetto-application listing geppetto-client between its dependencies in package.json.

Also because geppetto-application is now where the frontend is built, we moved webpack.config.js to this repo, and now this can be used as a starting point to create custom Geppetto frontends.
