### ISSUE TITLE
Is Geppetto maintained and still working?

### ISSUE THREAD

**Issue by lamerman** [openworm/org.geppetto#635]
Hi I tried to run Geppetto locally to run my experiments and visualize them. I followed this guide, but with not much of success
 http://docs.geppetto.org/en/latest/osxlinuxsetup.html .

It looks like the app javascript code and the server code are somehow out of sync. I get errors here and there, fixing one in the code I get another and there seem to be no end to it. :(

So the question is, that manual that you provided, is it still valid, do you expect it to work? 

Is there maybe some docker image that has the working version of backend, frontend and the database? So I can simply run something without spending much of the time on problem resolution.

Thank you!

**Comment by tarelli** [comment]
@lamerman thanks for trying Geppetto, yes the project is still active and working. Those instructions though will get you locally the equivalent of visiting https://live.geppetto.org/  (the docker files are here https://github.com/openworm/org.geppetto/tree/master/utilities/docker) which at this stage is just an old demo of something that you could build with geppetto. I would recommend just looking at what is deployed on live rather than setting up anything locally since it will save you some time. The main point is that Geppetto has evolved to be a platform to help build neuroscience applications (see the paper http://paper.geppetto.org/) rather than an application per se so nowadays it is targeted at software developers and unless you want to start your own software project using geppetto there is little use to set anything up locally. Some recent examples of applications built with Geppetto that you can try:

https://v2.virtualflybrain.org
http://nwbexplorer.opensourcebrain.org

**Comment by lamerman** [comment]
Thank you @tarelli !
I looked at several applications using Geppetto before trying to make a local version, including https://live.geppetto.org/  and opensourcebrain.org . 

https://live.geppetto.org/ does not provide a way to run my own experiment, while opensourcebrain.org looks a bit slow and sometimes didn't perform what I wanted, plus it obliges you to make a github project for everything.

So I though just a local installation of some sample Geppetto application with the persistence module and simulation would be basically a perfect thing for me, to make some model, run the simulation with neuron and then visualize it.

But ok, thank again.
