### ISSUE TITLE
Compression of data transfer between server and client

### ISSUE THREAD

**Issue by vellamike** [openworm/org.geppetto#9]
During the resolution of https://github.com/openworm/org.geppetto/issues/8 @tarelli @gidili and I realised that large SPH scenes result in a communications bottleneck. We decided that simulation information sent from server to client needs to be compressed in some way. I'll start the ball rolling with some ideas of how to do this:

1. Binary not JSON
2. Data compression
3. Select "rendering particles" at configuration stage - only these are sent, the others are used in calculation only.
4. Work out 3D Convex hulls of particles and send only those
5. Only send particles which have moved by a significant distance. The server will need to keep track of what has been displayed on the client.

**Comment by tarelli** [comment]
@domenic do you still think you would have some time to help with this? :) the next Geppetto meeting will be on the 20th of January at 4pm GMT

**Comment by frenkield** [comment]
I did some experimentation with a compressed binary protocol. I also moved message compression and transmission into separate threads. On an EC2 GPU instance (g2.2xlarge) I'm getting about 8 fps in the browser for sphModel_Elastic.xml. This model has 16974 liquid particles and 1575 elastic particles.

Model: sphModel_Elastic.xml
Liquid particles: 16974
Elastic particles: 1575
Browser fps: 8
JSON scene size: 5mb
JSON compressed scene size: 700kb
Binary scene size (doubles): 600kb
Binary compressed scene size: 260kb
Binary compression time: 55ms
SPH fps: 26ms

The binary representation is just 4 doubles per particle. One double for particle id and type, and 3 doubles for position. I haven't tried this with floats yet but I assume the compressed size would be around 200kb.

The g2.2xlarge is doing the whole SPH computation step in 26ms but the transport thread is only sending at about 8 fps. This is partly due to the 55ms required for message compression. But it seems like there are some other bottlenecks somewhere. Maybe I can get this up to 10 or 12 fps with a bit of refactoring.

The latest version of Virgo (3.6.3) supports the JSR-356 Java WebSocket 1.0 implementation. This has per-message deflate so that would eliminate the need for explicit compression. Chrome supports per-message deflate and maybe Firefox does as well but I'm not quite sure. So upgrading to Virgo 3.6.3 and refactoring GeppettoServlet to use JSR-356 might provide a good performance boost for the current implementation without any other code changes. I'm planning to give this a try next.

**Comment by gidili** [comment]
@frenkield that sounds quite promising, for comparison how many fps do you get in browser for the small elastic and small liquid scenes (default Geppetto samples) with the same setup?

Thanks for looking into this, sorting it would be a major improvement!

**Comment by frenkield** [comment]
@gidili, I'm seeing up to 200 fps (scene frames processed per second really) with the small elastic scene. The small liquid scene is broken at the moment. I'll take a look later tonight and get that resolved.

I can leave it running for a few hours tomorrow if you want to take a look.

**Comment by gidili** [comment]
@frenkield yes that would be interesting if you get the chance, thanks. Are you doing this in your fork of org.geppetto.frontend?

What you are doing sounds like exactly what we have been wanting to try to test the limits of this approach with the smaller size of the data transferred but the additional compress / decompress time. Even more interesting in the case of the deflate option. Regardless, this should greatly improve most simulations and enable us to stream simulations that were only possible locally to the server or over local network. 

After we test the limits of this approach, in terms of scene size, we can start working on other strategies to further reduce the amount of data sent (various configurable downsampling) by real-time simulators. At the same time we are introducing in Geppetto the capability to trigger simulations asynchronously for very big / computational intensive stuff using external simulators. Simulations will be queued and when completed a recording file with simulation data will be saved. The recording file will be then "played" at a later time, and the simulation will be then streamed to the client, so these improvements will be still relevant to optimising all sorts of scenarios.

**Comment by frenkield** [comment]
@gidili, that sounds great. You guys have a lot of very interesting problems to solve. I'm glad I can help out.

You can check out the compressed protocol demo here:
* http://23.23.241.249:8080/org.geppetto.frontend/?sim=file:///home/ec2-user/samples/SmallLiquid.xml
* http://23.23.241.249:8080/org.geppetto.frontend/?sim=file:///home/ec2-user/samples/LiquidAndElastic.xml
* http://23.23.241.249:8080/org.geppetto.frontend/?sim=file:///home/ec2-user/samples/BigLiquid.xml

A few notes:
* I included the URL for the small liquid scene because the one that runs from the dropdown doesn't start. Everything is fine for me locally but on the EC2 instance it's broken. This happens on the clean Geppetto 0.2.2 release as well. I assume it's because it starts immediately after load but I haven't really looked into it. I might install the Oracle JDK to see if that changes anything.
* I set updateCycle in the simulation bundle to 0. The default value is 20 so there's normally a minimum 20ms between frames.
* It's logging fps in the console. I put some crude timing in the websocket onMessage callback.
* The scene still loads with the uncompressed JSON so the initial load is slow for the larger scenes.

**Comment by frenkield** [comment]
Sorry, forgot to answer your question. Yes, I forked org.geppetto.frontend - and a few others as well. The bulk of the changes are in org.geppetto.frontend and org.geppetto.simulation.

**Comment by gidili** [comment]
@frenkield just tried your samples, looks like major improvements on both the small scene (goes much faster than the one on live.geppetto.org) and the big ones! Some of the gains (on the small scenes) may come from the fact that you are using a more powerful instance compared to live but the big scenes in particular are rendering at speed comparable to running on localhost in my experience if not slightly faster, which is a great result considering we are streaming over the internet. I am noticing a few glitches with simulation controls (unresponsive pause / start / stop buttons, could be just triggered by scene size) but other than that this is an impressive improvement already!

I will have a look at the code as soon as I can but I am eager to see what happens with the your other experiments with deflate and talk about how we can plan for some version of this to make into the dev branch of geppetto. You should join us at the next Geppetto dev meeting to discuss this :)

cc: @tarelli

**Comment by frenkield** [comment]
I think the unresponsiveness is due to the queuing of messages for transmission. For the large scenes the transmission rates don't quite keep up with the SPH solver so messages get queued up. The queue size is 20 so when you click stop, for example, the browser still has 20 frames it needs to process.

If the queue is full the transmission thread tosses out the oldest scene update when adding a new one. So you'll see skipped frames in the browser. This was the simplest thing for now but I imagine it's often preferable to preserve all frames and have the solver wait. 

In any case the code will definitely need to be refactored. I jammed it in where it seemed easiest for now.

And thank you, I'd definitely like to attend the next dev meeting. When is it?

**Comment by gidili** [comment]
@frenkield understood! The next meeting is Tuesday April-14 4-6pm GMT. It's every second Tuesday at the same time. If you can't make that one we can organize another chat just to discuss this improvements you're prototyping. If you send me an email at giovanni-at-openworm.org I will invite you to the Geppetto standing meeting and/or schedule something else if that doesn't work for you.

**Comment by tarelli** [comment]
@frenkield thanks a lot for this, as you could probably see from the history this is an old one. 
We can update the script and what gets released to Virgo 3.6.3 no problem. 

I was looking at the code, in particular I wonder if we need something which seems [adhoc for scenes with particles](https://github.com/frenkield/org.geppetto.frontend/blob/c52263d84461af93726c0e0b6328634c8b1a51a5/src/main/java/org/geppetto/frontend/controllers/MessageSenderService.java#L118) or if we can find a more generic catch all kind of solution as we'll be streaming loads of numbers also in other simulations that have no particles at all. 

I'm looking forward to meeting you at the Geppetto meeting next Tuesday, thanks again for helping with this!

**Comment by frenkield** [comment]
@tarelli, my pleasure. It's all super interesting.

I tried Virgo 3.6.3 and sadly it uses a version of Tomcat (7.0.53) that doesn't support the deflate option. The deflate option was added in Tomcat 7.0.56 so I assume the next Virgo release will include it. So that feature will probably have to wait. But I'm gonna try to get the 7.0.56 deflate functionality going in Virgo just to see if it actually works.

And yeah, my solution is far from optimal. It's gotta be completely refactored. I think maybe it should be divided into 4 separate features/changes:

1. Move JSON serialization and message transmission into separate threads. This is pretty minor since it doesn't affect the protocol at all. And it doesn't involve any changes on the client. Currently the solver waits around a bit for message transmission to complete so this change alone helps performance.
2. Add compression to the JSON protocol. This requires changes on both server and client but it keeps the protocol intact so it's not super invasive.
3. Add the binary protocol. My current solution is really basic. Someone above in the thread suggested using protocol buffers so that might make it pretty straightforward.
4. When Virgo support it, remove the manual compression in favor of websocket deflate. 

Thanks!

**Comment by tarelli** [comment]
At the Geppetto meeting we agreed with @frenkield to go ahead with the following two points. We'll capture the remaining two in separate cards.
- [ ] Move JSON serialization and message transmission into separate threads. This is pretty minor since it doesn't affect the protocol at all. And it doesn't involve any changes on the client. Currently the solver waits around a bit for message transmission to complete so this change alone helps performance.
- [ ] Add compression to the JSON protocol. This requires changes on both server and client but it keeps the protocol intact so it's not super invasive.

**Comment by tarelli** [comment]
@frenkield how is this going?  let me know if I can help in any way!

**Comment by frenkield** [comment]
@tarelli, it's going ok. I have it all working and reasonably well organized.

At the moment I'm trying to add some facilities to make the UI more responsive. Because of the message queuing the UI lags when viewing large scenes. Hopefully I'll have that all going tonight.

**Comment by vellamike** [comment]
Really happy to see this resolved :)

**Comment by parthipanr** [comment]
Is there any method to decompress the gzip compressed data in client side??

**Comment by tarelli** [comment]
@parthipanr we are using a library called [pako](http://nodeca.github.io/pako/0)

**Comment by vellamike** [comment]
you have a typo  - [pako](http://nodeca.github.io/pako)
